name: Notify of any website changes

on:
  schedule:
  - cron: '55 12 * * *'

jobs:
  notify:

    runs-on: ubuntu-latest


    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: pip install -r requirements.txt
              
      - name: Web site changes
        run: python web.py
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4